"use client";
import {
  useReactTable,
  getCoreRowModel,
  flexRender,
} from "@tanstack/react-table";

const Table = () => {
  const data = [
    {
      id: 1,
      first_name: "Yardley",
      last_name: "Labrum",
      email: "ylabrum0@wisc.edu",
      gender: "Male",
    },
    {
      id: 2,
      first_name: "Burgess",
      last_name: "Connerry",
      email: "bconnerry1@independent.co.uk",
      gender: "Male",
    },
    {
      id: 3,
      first_name: "Mathian",
      last_name: "Heffy",
      email: "mheffy2@ox.ac.uk",
      gender: "Male",
    },
    {
      id: 4,
      first_name: "Shirleen",
      last_name: "Graber",
      email: "sgraber3@uiuc.edu",
      gender: "Female",
    },
    {
      id: 5,
      first_name: "Antony",
      last_name: "McCrea",
      email: "amccrea4@hibu.com",
      gender: "Male",
    },
    {
      id: 6,
      first_name: "Lyndsie",
      last_name: "Wheatman",
      email: "lwheatman5@people.com.cn",
      gender: "Polygender",
    },
    {
      id: 7,
      first_name: "Franchot",
      last_name: "Corbally",
      email: "fcorbally6@washingtonpost.com",
      gender: "Male",
    },
    {
      id: 8,
      first_name: "Alister",
      last_name: "Pickin",
      email: "apickin7@privacy.gov.au",
      gender: "Male",
    },
    {
      id: 9,
      first_name: "Reinwald",
      last_name: "Raffles",
      email: "rraffles8@sakura.ne.jp",
      gender: "Agender",
    },
    {
      id: 10,
      first_name: "Vernen",
      last_name: "Allibone",
      email: "vallibone9@t-online.de",
      gender: "Male",
    },
    {
      id: 11,
      first_name: "Guy",
      last_name: "Round",
      email: "grounda@netscape.com",
      gender: "Male",
    },
    {
      id: 12,
      first_name: "Merola",
      last_name: "Fitter",
      email: "mfitterb@imdb.com",
      gender: "Female",
    },
    {
      id: 13,
      first_name: "Shem",
      last_name: "Pischoff",
      email: "spischoffc@theguardian.com",
      gender: "Male",
    },
    {
      id: 14,
      first_name: "Demeter",
      last_name: "Kilborn",
      email: "dkilbornd@slate.com",
      gender: "Female",
    },
    {
      id: 15,
      first_name: "Nealon",
      last_name: "Pickerin",
      email: "npickerine@globo.com",
      gender: "Male",
    },
    {
      id: 16,
      first_name: "Paige",
      last_name: "Sealove",
      email: "psealovef@1und1.de",
      gender: "Female",
    },
    {
      id: 17,
      first_name: "Hugibert",
      last_name: "Chatain",
      email: "hchataing@independent.co.uk",
      gender: "Male",
    },
    {
      id: 18,
      first_name: "Pernell",
      last_name: "Cowhig",
      email: "pcowhigh@pbs.org",
      gender: "Male",
    },
    {
      id: 19,
      first_name: "Patience",
      last_name: "Willans",
      email: "pwillansi@slate.com",
      gender: "Female",
    },
    {
      id: 20,
      first_name: "Phylis",
      last_name: "Speachley",
      email: "pspeachleyj@yandex.ru",
      gender: "Polygender",
    },
    {
      id: 21,
      first_name: "Celestina",
      last_name: "Ferrick",
      email: "cferrickk@wisc.edu",
      gender: "Female",
    },
    {
      id: 22,
      first_name: "Lonni",
      last_name: "Borwick",
      email: "lborwickl@rakuten.co.jp",
      gender: "Female",
    },
    {
      id: 23,
      first_name: "Ardith",
      last_name: "Goldes",
      email: "agoldesm@facebook.com",
      gender: "Female",
    },
    {
      id: 24,
      first_name: "Neel",
      last_name: "Cordelle",
      email: "ncordellen@soundcloud.com",
      gender: "Male",
    },
    {
      id: 25,
      first_name: "Noel",
      last_name: "Landes",
      email: "nlandeso@samsung.com",
      gender: "Bigender",
    },
    {
      id: 26,
      first_name: "Les",
      last_name: "Audas",
      email: "laudasp@pagesperso-orange.fr",
      gender: "Non-binary",
    },
    {
      id: 27,
      first_name: "Beau",
      last_name: "Folomkin",
      email: "bfolomkinq@jimdo.com",
      gender: "Male",
    },
    {
      id: 28,
      first_name: "Ronny",
      last_name: "Elgram",
      email: "relgramr@51.la",
      gender: "Female",
    },
    {
      id: 29,
      first_name: "Sayer",
      last_name: "Moston",
      email: "smostons@toplist.cz",
      gender: "Non-binary",
    },
    {
      id: 30,
      first_name: "Miran",
      last_name: "Blaxill",
      email: "mblaxillt@elpais.com",
      gender: "Female",
    },
    {
      id: 31,
      first_name: "Jeni",
      last_name: "Castaignet",
      email: "jcastaignetu@pen.io",
      gender: "Female",
    },
    {
      id: 32,
      first_name: "Janaye",
      last_name: "MacAndie",
      email: "jmacandiev@nyu.edu",
      gender: "Female",
    },
    {
      id: 33,
      first_name: "Dorey",
      last_name: "Rizzardi",
      email: "drizzardiw@intel.com",
      gender: "Male",
    },
    {
      id: 34,
      first_name: "Becky",
      last_name: "Lunnon",
      email: "blunnonx@globo.com",
      gender: "Female",
    },
    {
      id: 35,
      first_name: "Svend",
      last_name: "Boatwright",
      email: "sboatwrighty@topsy.com",
      gender: "Male",
    },
    {
      id: 36,
      first_name: "Gav",
      last_name: "Ruegg",
      email: "grueggz@macromedia.com",
      gender: "Male",
    },
    {
      id: 37,
      first_name: "Hilary",
      last_name: "Kidd",
      email: "hkidd10@ft.com",
      gender: "Non-binary",
    },
    {
      id: 38,
      first_name: "Trace",
      last_name: "Girault",
      email: "tgirault11@jimdo.com",
      gender: "Male",
    },
    {
      id: 39,
      first_name: "Teodoro",
      last_name: "Finlator",
      email: "tfinlator12@imageshack.us",
      gender: "Male",
    },
    {
      id: 40,
      first_name: "Stefa",
      last_name: "Jamieson",
      email: "sjamieson13@ycombinator.com",
      gender: "Female",
    },
    {
      id: 41,
      first_name: "Cob",
      last_name: "Skrine",
      email: "cskrine14@bigcartel.com",
      gender: "Male",
    },
    {
      id: 42,
      first_name: "Teddie",
      last_name: "Hackley",
      email: "thackley15@epa.gov",
      gender: "Male",
    },
    {
      id: 43,
      first_name: "Brent",
      last_name: "Waszkiewicz",
      email: "bwaszkiewicz16@baidu.com",
      gender: "Male",
    },
    {
      id: 44,
      first_name: "Arri",
      last_name: "Dolley",
      email: "adolley17@cafepress.com",
      gender: "Male",
    },
    {
      id: 45,
      first_name: "Bernardine",
      last_name: "Spillane",
      email: "bspillane18@sohu.com",
      gender: "Female",
    },
    {
      id: 46,
      first_name: "Fayth",
      last_name: "Klimpke",
      email: "fklimpke19@ezinearticles.com",
      gender: "Female",
    },
    {
      id: 47,
      first_name: "Duane",
      last_name: "Theis",
      email: "dtheis1a@mac.com",
      gender: "Male",
    },
    {
      id: 48,
      first_name: "Joletta",
      last_name: "Doody",
      email: "jdoody1b@com.com",
      gender: "Female",
    },
    {
      id: 49,
      first_name: "Gregor",
      last_name: "Kimblen",
      email: "gkimblen1c@cbslocal.com",
      gender: "Male",
    },
    {
      id: 50,
      first_name: "Leighton",
      last_name: "Maddern",
      email: "lmaddern1d@about.com",
      gender: "Male",
    },
  ];

  const table = useReactTable({ data, columns });
  return <div className="py-16">Table</div>;
};

export default Table;
